### ISSUE TITLE
!Run file requirements are incorrect

### ISSUE THREAD

**Issue by gerph** [usr-bin-gcc/throwback#1]
You've got requirements in your !Run file saying that you require DDEUtils 1.75 or higher. Versions of DDEUtils going back as far as (in my history) 1.56 support the register/unregister interface that you're using. And strictly, and task can send the messages.

I don't know when the DDEUtils started supporting the task registration process, but at least 1.56 has these calls.

**Comment by usr-bin-gcc** [comment]
cheers, much appreciated!  I'll change them to 1.56 (might take me a while, I am new to github as well as RiscOS desktop programming ;o)

**Comment by gerph** [comment]
No problem; you asked for comments :-) (found the project, 'cos I keep an eye on github projects with the `riscos` topic).

To fix on github, you can actually create a change directly, I think; if you go to the file in the code view, then on the right hand side of the file's top bar you should see a little pen 'edit' icon, which should let you make a change and either create a branch for it, or directly commit to the master branch. That way it can be fixed up quite quickly.

Then, on the computer which has the original git repo, you'll need to do a `git pull` to retrieve the change that you made in the Web UI.

**Comment by usr-bin-gcc** [comment]
The more feedback, the better!  I've updated it directly this time, and will try making a branch for the other one.  I haven't set up a repo yet, but probably should.
