### ISSUE TITLE
Font handle leakage

### ISSUE THREAD

**Issue by gerph** [usr-bin-gcc/throwback#2]
It looks like the font handles are being leaked by the text pane; they're claimed in the _Create function but never released with `font_losefont` in `_Destroy`. Additionally, you would need to re-find the fonts whenever a mode change was received, as the handle may be incorrect in the new mode (consider the mode may have different dimensions of the pixels, which would mean that your font would appear squashed or stretched).

You might find it easier to use `Wimp_TextOp` in this case to plot the text in the configured wimp font. Since you're using it as a diagnostic interface, this would not be inappropriate, but would mean that characters wouldn't line up. Otherwise, you might want to just add a `font_losefont` to the Destroy and add a message handler for the mode change to reclaim fonts in any of the textpanes you've created.

**Comment by usr-bin-gcc** [comment]
Thanks for the helpful feedback.  I'll add the losefont in _Destroy as you suggest, and investigate the mode change notification, but the Wimp_TextOp sounds useful for another program, so I will investigate that as well.
